base: 'https://typo3-14-demo.ddev.site/'
dependencies:
  - wmgraphix/sitepackage
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.utf8
    navigationTitle: Deutsch
    flag: de
    hreflang: de-DE
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
